Sys_Ingresos/Sys_Ingresos/Controllers/SIAEController.cs
using Sys_Ingresos.Data.Cuotas;
using Sys_Ingresos.Models;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Net.Mime;
using System.Net.Mail;
using Sys_Ingresos.Models.JWT;
using System.IdentityModel.Tokens.Jwt;

namespace Sys_Ingresos.Controllers
{
    public class SIAEController : Controller
    {
        // GET: SIAE
        SESION SesionUsu = new SESION();
        SCE_CUOTAS_POSGRADO_DATOS SesionCuota = new SCE_CUOTAS_POSGRADO_DATOS();
       
        public ActionResult CuotasPosgrado()
        {
            return View();
        }

        public ActionResult PagosPosgrado()
        {
            return View();
        }

        public ActionResult CuotasLenguas()
        {
            return View();
        }

        public ActionResult CuotasPosgradoRegistro()
        {
            return View();
        }

        public ActionResult PagosSYSWEB_a_SIAE()
        {
            return View();
        }

        public ActionResult Referencias()
        {
            return View();
        }


        public JsonResult ObtCuotaPosgrado(int Id)
        {
            string Verificador = string.Empty;
            var Lista = ObtenerDataContext.ObtenerDatosCuotas(Id, ref Verificador);
            if(Verificador=="0")
                return Json(Lista, JsonRequestBehavior.AllowGet);
            else
                return Json(false, JsonRequestBehavior.AllowGet);


        }



        public JsonResult ObtCuotaLenguas(int Id)
        {
            RESULTADO_CUOTAS_SABATINOS objResultado = new RESULTADO_CUOTAS_SABATINOS();

            try
            {
                string Verificador = string.Empty;
                var Lista = ObtenerDataContext.ObtenerDatosCuotaLenguas(Id, ref Verificador);
                if (Verificador == "0")
                {
                    objResultado.ERROR = false;
                    objResultado.MENSAJE_ERROR = "";
                    objResultado.RESULTADO = Lista;
                    return Json(objResultado, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    objResultado.ERROR = true;
                    objResultado.MENSAJE_ERROR = Verificador;
                    objResultado.RESULTADO = null;
                    return Json(objResultado, JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception ex)
            {
                objResultado.ERROR = true;
                objResultado.MENSAJE_ERROR = ex.Message;
                objResultado.RESULTADO = null;
                return Json(objResultado, JsonRequestBehavior.AllowGet);
            }
    }

    //public JsonResult ObtUsuario()
    //{
    //    string Verificador = string.Empty;
    //    //if (Request.QueryString["WXI"] != null)
    //    //    SesionUsu.UsuWXI = Request.QueryString["WXI"];
    //    //else
    //    //    SesionUsu.UsuWXI = "0";

    //    if (Session["UsuarioIng"] != null)
    //        SesionUsu = (SESION)System.Web.HttpContext.Current.Session["UsuarioIng"];


    //    var Lista=ObtenerDataContext.ObtenerUsuario(SesionUsu.UsuWXI, ref Verificador);
    //    if (Verificador == "0")
    //    {
    //        SesionUsu.Usu_Nombre = Lista[0].USUARIO;
    //        System.Web.HttpContext.Current.Session["UsuarioIng"] = SesionUsu;
    //        return Json(Lista, JsonRequestBehavior.AllowGet);
    //    }
    //    else
    //        return Json("RERROR"+ Request.QueryString["WXI"] + Verificador, JsonRequestBehavior.AllowGet);
    //}

        public JsonResult ObtUsuario()
        {
            string Verificador = string.Empty;
            List<GRL_USUARIOS> Lista = new List<GRL_USUARIOS>();
            GRL_USUARIOS objUsuario = new GRL_USUARIOS();
            if (Session["UsuarioIng"] != null)
            {
                SesionUsu = (SESION)System.Web.HttpContext.Current.Session["UsuarioIng"];
                objUsuario.NOMBRE = SesionUsu.Usu_Nombre;
                objUsuario.TIPO = SesionUsu.Tipo;
                Lista.Add(objUsuario);
                return Json(Lista, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("Usuario Incorrecto.", JsonRequestBehavior.AllowGet);
        }

        public JsonResult GuardarCuotaSel(int Cve, string Generacion, int Selec)
        {
            string ClaseTipoUsu = string.Empty;
            SCE_CUOTAS_POSGRADO_DATOS objCuotas = new SCE_CUOTAS_POSGRADO_DATOS();
            List<SCE_CUOTAS_POSGRADO_DATOS> ListCuotas;
            try
            {
                objCuotas.ID = Cve;
                objCuotas.GENERACION = Generacion;

                if (Session["CuotasSel"] == null)
                {
                    ListCuotas = new List<SCE_CUOTAS_POSGRADO_DATOS>();
                    ListCuotas.Add(objCuotas);
                }
                else
                {
                    ListCuotas = (List<SCE_CUOTAS_POSGRADO_DATOS>)Session["CuotasSel"];
                    if (Selec == 1)
                        ListCuotas.Add(objCuotas);
                    else 
                        ListCuotas.RemoveAll(x => x.ID == Cve && x.GENERACION == Generacion);
                    
                }

                Session["CuotasSel"] = ListCuotas;
                return Json("S", JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("N", JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult EliminarCuotasSel(string Generacion)
        {
            string Verificador = string.Empty;
            List<SCE_CUOTAS_POSGRADO_DATOS> ListCuotas;

            if (Session["CuotasSel"] == null)
            {
                return Json("Seleccionar al menos una cuota.", JsonRequestBehavior.AllowGet);
            }
            else
            {
                ListCuotas = (List<SCE_CUOTAS_POSGRADO_DATOS>)Session["CuotasSel"];
                GuardarDataContext.EliminarCuotasSel(Generacion, ListCuotas, ref Verificador);
                if (Verificador == "0")
                {
                    Session["CuotasSel"] = null;
                    return Json("0", JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(Verificador, JsonRequestBehavior.AllowGet);
            }


            //return Json("S", JsonRequestBehavior.AllowGet);

        }

        public JsonResult ListarTipoUsu()
        {
            string ClaseTipoUsu = string.Empty;

            if (Session["UsuarioIng"] != null)
            {
                SesionUsu = (SESION)System.Web.HttpContext.Current.Session["UsuarioIng"];
                return Json(SesionUsu.Tipo, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("N", JsonRequestBehavior.AllowGet);
        }

        public JsonResult ListarCuotasPosgrado(string Dependencia, string Carrera)
        {
            string ClaseTipoUsu = string.Empty;

            if (Session["UsuarioIng"] != null)
                SesionUsu = (SESION)System.Web.HttpContext.Current.Session["UsuarioIng"];

            if (SesionUsu.Tipo == "SA")
                ClaseTipoUsu = "";
            else
                ClaseTipoUsu = "hidden";

            var Lista = GridDataContext.ObtenerCuotasPosgrado(Dependencia, Carrera);
            List<SCE_CUOTAS_POSGRADO> list = new List<SCE_CUOTAS_POSGRADO>();
            if (Lista.GRUPO.Count > 0)
            {
                
                SCE_CUOTAS_POSGRADO dc = new SCE_CUOTAS_POSGRADO();
                {
                    var generacion = Lista.GRUPO.Select(c => new
                    {
                        c.GENERACION,
                        c.DESC_GENERACION,
                        ClaseTipoUsu,
                        c.RUTA_ADJUNTO,
                        Datos = c.CUOTAS.Select(s => new
                        {
                            s.ID,
                            s.NO_PAGO,
                            s.SEMESTRE,
                            s.CONCEPTO_DESCRIPCION,
                            s.CUOTA,
                            s.VALOR,
                            s.FECHA_LIMITE,
                            s.CUOTA_PAQUETE,
                            s.NO_PAQUETE,
                            s.TIPO_PROGRAMA,
                            ClaseTipoUsu
                        })
                    });
                    return new JsonResult
                    {
                        Data = generacion,
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet
                    };
                }
            }

            return Json(Lista, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ListarCuotasSabatinosLenguas(string Escuela, string Tipo)
        {
            RESULTADO_CUOTAS_SABATINOS objResultado = new RESULTADO_CUOTAS_SABATINOS();

            try
            {
                var Lista = GridDataContext.ObtenerCuotasLenguasSabatinos(Escuela, Tipo);
                objResultado.ERROR = false;
                objResultado.MENSAJE_ERROR = "";
                objResultado.RESULTADO = Lista;
                return Json(objResultado, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                objResultado.ERROR = true;
                objResultado.MENSAJE_ERROR = ex.Message;
                objResultado.RESULTADO = null;
                return Json(objResultado, JsonRequestBehavior.AllowGet);
            }
        }



        public JsonResult ListarEscuelas()
        {

            if (Session["UsuarioIng"] != null)
                SesionUsu = (SESION)System.Web.HttpContext.Current.Session["UsuarioIng"];


            //SesionUsu = System.Web.HttpContext.Current.Session["UsuarioIng"] as SESION;

Sys_Ingresos/Sys_Ingresos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.min.css" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    @*<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.3.1.js"></script>*@

    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/charts.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/material.js"></script>
    <script src="https://www.amcharts.com/lib/4/lang/de_DE.js"></script>
    <script src="https://www.amcharts.com/lib/4/geodata/germanyLow.js">
    </script>
    <script src="//www.amcharts.com/lib/4/themes/animated.js"></script>


    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/Precarga.css">
    @*<link rel="stylesheet" type="text/css" href="~/Content/mdb.css">*@

    <script>
        function inicio() {
            alert("pasa");
            $('.datatables').DataTable();
        }

        function todo(objeto) {
            var celdas = $('#example').dataTable().api().cells().nodes();

            $(celdas).find(':checkbox').prop('checked', objeto.checked);
        }

        function enviar_form() {
            return false;
        }
    </script>
</head>
<body>
    <div>
        @*<div class="navbar navbar-inverse navbar-fixed-top">
                <div>
                    <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="menu-item dropdown btn-primary">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Posgrado<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Cuotas", "CuotasPosgrado", "SIAE")</li>
                                        <li>@Html.ActionLink("Pagos", "PagosPosgrado", "SIAE")</li>
                                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                </div>
            </div>*@




    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    @*<script src="~/Scripts/angular.min.js"></script>*@
    <script src="~/Scripts/global.js"></script>
    <script src="~/Scripts/checklist-model.js"></script>
    @*<script src="~/Scripts/angular.js"></script>*@
    <script src="~/Scripts/angular.ng-modules.js"></script>
    <script src="~/Scripts/Models/PlantillaModel.js"></script>
    <script src="~/Scripts/Controllers/PlantillaController.js"></script>
    <script src="~/Scripts/application.js"></script>
    <link href="~/Scripts/select2/css/select2.min.css" type="text/css" rel="stylesheet" />
    <script src="~/Scripts/select2/js/select2.min.js"></script>
    @*<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.3.1.js"></script>*@

    @*@RenderPage("~/Views/Shared/_Footer.cshtml")*@
</body>
</html>